Wiremock
wolox-training/cm-java pull request #22
Opened 2021-05-25 22:46 UTC by carolinaWolox

## Summary
- Mock on wiremock
## Trello Card
https://trello.com/c/IJLEx7VK/43-mockear-respuestas-con-wiremock

2021-05-26 15:40 UTC, juanwongramirez approved these changes
God Job!

2021-05-26 18:50 UTC, julianvasquez-wolox requested changes

2021-05-26 18:50 UTC, julianvasquez-wolox commented on src/main/java/wolox/training/service/OpenLibraryService.java
> -                .getForObject(Constants.URL_EXTERNAL_API + isbn + Constants.URL_EXTERNAL_API_PARAM, String.class);
by changing this URL for a localhost you are making the tests work but the application will fail since it's not consuming the external API. You could set a property to set the localhost just for the test, but the service should keep the external API address

2021-05-26 22:27 UTC, carolinaWolox commented on src/main/java/wolox/training/service/OpenLibraryService.java
> -                .getForObject(Constants.URL_EXTERNAL_API + isbn + Constants.URL_EXTERNAL_API_PARAM, String.class);
A possible solution was commit minutes ago, I expect your review and comments if you agree with that.
Thanks a lot!

2021-05-27 14:27 UTC, julianvasquez-wolox approved these changes

2021-05-27 14:36 UTC, merged